### ISSUE TITLE
rwkv5-lora finetuning OOM

### ISSUE THREAD

**Issue by xinyinan9527** [OpenMOSE/RWKV5-LM-LoRA#2]
首先，想请教有没有requirement.txt文件。因为之前训练没有问题，后面环境更换了之后按照
# Found torch 1.13.0a0+340c412, recommend 1.13.1+cu117 or newer
# Found deepspeed 0.12.6, recommend 0.7.0 (faster than newer versions)
# Found pytorch_lightning 1.9.5, recommend 1.9.5
参数设置为
`python train.py --load_model ""\
 --wandb "" --proj_dir "output_7B"\
 --data_file ""\
 --data_type "binidx" --vocab_size 65536 --ctx_len 4096 \
 --epoch_steps 200 --epoch_count 500 --epoch_begin 187 --epoch_save 1 \
 --micro_bsz 1  --n_layer 32 --n_embd 4096\
 --lr_init 4e-5 --lr_final 2e-5 \
 --warmup_steps 0 --beta1 0.9 --beta2 0.999 --adam_eps 1e-8 --my_exit_tokens 435242630 --magic_prime 106217 \
 --accelerator gpu --devices 2 --precision bf16\
 --strategy deepspeed_stage_2 \
 --grad_cp 1 --my_testing "r2r3r4" \
 --lora --lora_r 64 --lora_alpha 128 --accumulate_grad_batches 2 --lora_dropout 0.01 \
  --lora_parts=att,ffn,time,ln # configure which parts to finetune`
训练开始会报OOM错误，7B-V2的模型，GPU是A100（80G）*2
`144 M     Trainable params
7.5 B     Non-trainable params
7.7 B     Total params
30,642.602Total estimated model params size (MB)
Epoch 0:   0%|                                                                                                                                                                   | 0/200 [00:00<?, ?it/s]
{'zero_allow_untested_optimizer': True, 'zero_optimization': {'stage': 2, 'contiguous_gradients': True, 'overlap_comm': True, 'allgather_partitions': True, 'reduce_scatter': True, 'allgather_bucket_size': 200000000, 'reduce_bucket_size': 200000000, 'sub_group_size': 1000000000000}, 'activation_checkpointing': {'partition_activations': False, 'cpu_checkpointing': False, 'contiguous_memory_optimization': False, 'synchronize_checkpoint_boundary': False}, 'aio': {'block_size': 1048576, 'queue_depth': 8, 'single_submit': False, 'overlap_events': True, 'thread_count': 1}, 'gradient_accumulation_steps': 2, 'train_micro_batch_size_per_gpu': 1, 'gradient_clipping': 1.0, 'bf16': {'enabled': True}}

Epoch 0:   0%|▋                                                                                                                                     | 1/200 [00:05<17:25,  5.26s/it, loss=2.160, lr=4e-5]
{'zero_allow_untested_optimizer': True, 'zero_optimization': {'stage': 2, 'contiguous_gradients': True, 'overlap_comm': True, 'allgather_partitions': True, 'reduce_scatter': True, 'allgather_bucket_size': 200000000, 'reduce_bucket_size': 200000000, 'sub_group_size': 1000000000000}, 'activation_checkpointing': {'partition_activations': False, 'cpu_checkpointing': False, 'contiguous_memory_optimization': False, 'synchronize_checkpoint_boundary': False}, 'aio': {'block_size': 1048576, 'queue_depth': 8, 'single_submit': False, 'overlap_events': True, 'thread_count': 1}, 'gradient_accumulation_steps': 2, 'train_micro_batch_size_per_gpu': 1, 'gradient_clipping': 1.0, 'bf16': {'enabled': True}}

/opt/conda/lib/python3.8/site-packages/pytorch_lightning/strategies/ddp.py:437: UserWarning: Error handling mechanism for deadlock detection is uninitialized. Skipping check.
  rank_zero_warn("Error handling mechanism for deadlock detection is uninitialized. Skipping check.")
Traceback (most recent call last):
  File "./RWKV5-LM-LoRA/RWKV-v5/train.py", line 358, in <module>
    trainer.fit(model, data_loader)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 608, in fit
    call._call_and_handle_interrupt(
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/call.py", line 38, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 650, in _fit_impl
    self._run(model, ckpt_path=self.ckpt_path)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1112, in _run
    results = self._run_stage()
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1191, in _run_stage
    self._run_train()
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1214, in _run_train
    self.fit_loop.run()
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/loops/fit_loop.py", line 267, in advance
    self._outputs = self.epoch_loop.run(self._data_fetcher)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 213, in advance
    batch_output = self.batch_loop.run(kwargs)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 88, in advance
    outputs = self.optimizer_loop.run(optimizers, kwargs)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 202, in advance
    result = self._run_optimization(kwargs, self._optimizers[self.optim_progress.optimizer_position])
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 249, in _run_optimization
    self._optimizer_step(optimizer, opt_idx, kwargs.get("batch_idx", 0), closure)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 370, in _optimizer_step
    self.trainer._call_lightning_module_hook(
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1356, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/core/module.py", line 1754, in optimizer_step
    optimizer.step(closure=optimizer_closure)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/core/optimizer.py", line 169, in step
    step_output = self._strategy.optimizer_step(self._optimizer, self._optimizer_idx, closure, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/strategies/ddp.py", line 280, in optimizer_step
    optimizer_output = super().optimizer_step(optimizer, opt_idx, closure, model, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/strategies/strategy.py", line 234, in optimizer_step
    return self.precision_plugin.optimizer_step(
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/plugins/precision/deepspeed.py", line 132, in optimizer_step
    closure_result = closure()
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 149, in __call__
    self._result = self.closure(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 144, in closure
    self._backward_fn(step_output.closure_loss)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 305, in backward_fn
    self.trainer._call_strategy_hook("backward", loss, optimizer, opt_idx)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1494, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/strategies/strategy.py", line 207, in backward
    self.precision_plugin.backward(closure_loss, self.lightning_module, optimizer, optimizer_idx, *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/plugins/precision/deepspeed.py", line 118, in backward
    deepspeed_engine.backward(tensor, *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1955, in backward
    self.optimizer.backward(loss, retain_graph=retain_graph)
  File "/opt/conda/lib/python3.8/site-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 2019, in backward
    self.loss_scaler.backward(loss.float(), retain_graph=retain_graph)
  File "/opt/conda/lib/python3.8/site-packages/deepspeed/runtime/fp16/loss_scaler.py", line 63, in backward
    scaled_loss.backward(retain_graph=retain_graph)
  File "/opt/conda/lib/python3.8/site-packages/torch/_tensor.py", line 396, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/opt/conda/lib/python3.8/site-packages/torch/autograd/__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: RuntimeError: CUDA out of memory. Tried to allocate 112.00 MiB (GPU 1; 79.15 GiB total capacity; 77.24 GiB already allocated; 73.69 MiB free; 77.82 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

At:
  /opt/conda/lib/python3.8/site-packages/torch/nn/functional.py(1243): dropout
  /opt/conda/lib/python3.8/site-packages/torch/nn/modules/dropout.py(58): forward
  /opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py(1130): _call_impl
  /RWKV5-LM-LoRA/RWKV-v5/src/model.py(130): forward
  /opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py(1130): _call_impl
  /RWKV5-LM-LoRA/RWKV-v5/src/model.py(268): forward
  /opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py(1130): _call_impl
 /RWKV5-LM-LoRA/RWKV-v5/src/model.py(355): forward
  /opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py(1130): _call_impl
  /opt/conda/lib/python3.8/site-packages/torch/utils/checkpoint.py(368): unpack`

猜测大概率是环境依赖的问题，或者是因为一些其他什么原因呢

**Comment by OpenMOSE** [comment]
try python 3.10 torch2.1 deepspeed=0.14 pytorch-lightning 1.9.5

**Comment by xinyinan9527** [comment]
> try python 3.10 torch2.1 deepspeed=0.14 pytorch-lightning 1.9.5

Nice!It works,but I still use python 3.8.

**Comment by OpenMOSE** [comment]
maybe no need LoRA for you. cause you have A100 x 2 haha
